version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
# version: "3.3"
# services:
#   mongodb:
#     image: mongo:5.0.2
#     restart: unless-stopped
#     # env_file: ./.env
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=root
#     ports:
#       - 27017:27017
#     volumes:
#       - db:/data/db
#   app:
#     depends_on:
#       - mongodb
#     build: ./bezkoder-app
#     restart: unless-stopped
#     # env_file: ./.env
#     ports:
#       - 6868:8080
#     environment:
#       - DB_HOST=mongodb
#       - DB_USER=root
#       - DB_PASSWORD=root
#       - DB_NAME=myInventory
#       - DB_PORT=27017
#     stdin_open: true
#     tty: true
# volumes:
#   db:
